# Generated by Django 4.2.1 on 2023-06-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
